# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed5020792e67db3de5d92a1fdd5d1597a78c0d905fc3d176f53fdaef49104179a82caa2dbe88c3bb7ccd040a15c1d3a83b350de1a4c4a7e751741d76ec175aa0

test:
  secret_key_base: e78bbe13d6b22a1b30a36ede487d94c0a1216ee4bfe3eda2353642e60253ba6c820dcfc611caff106037b5500a9e7a7d70e72fc4c1e1d6c5f9f5257c9ff3859d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
